import { ReactionMetadata } from "./types";

export const reactionsMap: ReactionMetadata[] = [
  {
    title: "OK!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "1.png",
  },
  {
    title: "YES!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "2.png",
  },
  {
    title: "NO!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "3.png",
  },
  {
    title: "COOL!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "4.png",
  },
  {
    title: "LOL!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "5.png",
  },
  {
    title: "NICE!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "6.png",
  },
  {
    title: "WHAT?",
    x: 650,
    y: 70,
    scale: 3,
    filename: "7.png",
  },
  {
    title: "WHY?",
    x: 650,
    y: 70,
    scale: 3,
    filename: "8.png",
  },
  {
    title: "GREAT!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "9.png",
  },
  {
    title: "LOL!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "10.png",
  },
  {
    title: "SURE!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "11.png",
  },
  {
    title: "LFC!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "12.png",
  },
  {
    title: "!CHIMP",
    x: 650,
    y: 70,
    scale: 3,
    filename: "13.png",
  },
  {
    title: "?",
    x: 650,
    y: 70,
    scale: 3,
    filename: "14.png",
  },
  {
    title: "WOW!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "15.png",
  },
  {
    title: "XD",
    x: 650,
    y: 70,
    scale: 3,
    filename: "16.png",
  },
  {
    title: "<3",
    x: 650,
    y: 70,
    scale: 3,
    filename: "17.png",
  },
  {
    title: "GM!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "18.png",
  },
  {
    title: "GN!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "19.png",
  },
  {
    title: "F4F",
    x: 650,
    y: 70,
    scale: 3,
    filename: "20.png",
  },
  {
    title: "WLTC!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "21.png",
  },
  {
    title: "G(Y)M!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "22.png",
  },
  {
    title: "HAPPY CHUESDAY",
    x: 650,
    y: 70,
    scale: 3,
    filename: "23.png",
  },
  {
    title: "I AM !CHIMP AND !CHIMP IS ME",
    scale: 0.9,
    x: 500,
    y: 100,
    filename: "I AM !CHIMP AND !CHIMP IS ME.png",
  },
  {
    title: "#CHOOSECUTE",
    scale: 0.9,
    x: 550,
    y: 100,
    filename: "CHOOSECUTE.png",
  },
  {
    title: "HAPPY 100K!",
    scale: 0.9,
    x: 550,
    y: 100,
    filename: "happy 100k.png",
  },
  // 27: {
  //   title: "WE ALWAYS !CHIMP",
  //   scale: 0.9,
  //   x: 550,
  //   y: 100,
  //   filename: "WE ALWAYS !CHIMP.gif",
  // },
  {
    title: "WELCOME!",
    scale: 0.7,
    x: 600,
    y: 100,
    filename: "welcome!.png",
  },
  {
    title: "THANKS!",
    scale: 0.7,
    x: 600,
    y: 100,
    filename: "thanks.png",
  },
  {
    title: "LFCHIMP!",
    scale: 0.7,
    x: 600,
    y: 100,
    filename: "LFCHIMP.png",
  },
  {
    title: "WEN MINT?",
    scale: 0.7,
    x: 600,
    y: 100,
    filename: "wen mint.png",
  },
  {
    title: "FEELING !CHIMPISH",
    scale: 0.8,
    x: 650,
    y: 70,
    filename: "feeling chimpish.png",
  },
  {
    title: "WE LOVE $PENGU",
    scale: 0.9,
    x: 700,
    y: 80,
    filename: "we love pengu.png",
  },
  {
    title: "$PENGU TO THE MOON!",
    scale: 0.9,
    x: 700,
    y: 80,
    filename: "pengu to the moon.png",
  },
  {
    title: "HAPPY CHRISTMAS EVE!",
    scale: 0.9,
    x: 550,
    y: 100,
    filename: "Happy Christmas Eve.png",
  },
  {
    title: "MERRY CHRISTMAS!",
    scale: 0.8,
    x: 600,
    y: 100,
    filename: "merry christmas.png",
  },
  {
    title: "MERRY CHIMPMAS!",
    scale: 0.8,
    x: 400,
    y: 100,
    filename: "Merry Chimpmas.png",
  },
  {
    title: "HAPPY NEW YEAR!",
    scale: 0.8,
    x: 600,
    y: 80,
    filename: "happy new year.png",
  },
  {
    title: "TOGETHER WE WHALE!",
    scale: 0.8,
    x: 600,
    y: 80,
    filename: "together we whale.png",
  },
];
