import { ReactionMetadata } from "./types";

export const reactionsMap: { [key: number]: string | ReactionMetadata } = {
  1: {
    title: "OK!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "1.png",
  },
  2: {
    title: "YES!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "2.png",
  },
  3: {
    title: "NO!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "3.png",
  },
  4: {
    title: "COOL!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "4.png",
  },
  5: {
    title: "LOL!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "5.png",
  },
  6: {
    title: "NICE!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "6.png",
  },
  7: {
    title: "WHAT?",
    x: 650,
    y: 70,
    scale: 3,
    filename: "7.png",
  },
  8: {
    title: "WHY?",
    x: 650,
    y: 70,
    scale: 3,
    filename: "8.png",
  },
  9: {
    title: "GREAT!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "9.png",
  },
  10: {
    title: "LOL!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "10.png",
  },
  11: {
    title: "SURE!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "11.png",
  },
  12: {
    title: "LFC!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "12.png",
  },
  13: {
    title: "!CHIMP",
    x: 650,
    y: 70,
    scale: 3,
    filename: "13.png",
  },
  14: {
    title: "?",
    x: 650,
    y: 70,
    scale: 3,
    filename: "14.png",
  },
  15: {
    title: "WOW!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "15.png",
  },
  16: {
    title: "XD",
    x: 650,
    y: 70,
    scale: 3,
    filename: "16.png",
  },
  17: {
    title: "<3",
    x: 650,
    y: 70,
    scale: 3,
    filename: "17.png",
  },
  18: {
    title: "GM!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "18.png",
  },
  19: {
    title: "GN!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "19.png",
  },
  20: {
    title: "F4F",
    x: 650,
    y: 70,
    scale: 3,
    filename: "20.png",
  },
  21: {
    title: "WLTC!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "21.png",
  },
  22: {
    title: "G(Y)M!",
    x: 650,
    y: 70,
    scale: 3,
    filename: "22.png",
  },
  23: {
    title: "HAPPY CHUESDAY",
    x: 650,
    y: 70,
    scale: 3,
    filename: "23.png",
  },
  24: {
    title: "I AM !CHIMP AND !CHIMP IS ME",
    scale: 0.9,
    x: 500,
    y: 100,
    filename: "I AM !CHIMP AND !CHIMP IS ME.png",
  },
  25: {
    title: "#CHOOSECUTE",
    scale: 0.9,
    x: 550,
    y: 100,
    filename: "CHOOSECUTE.png",
  },
  26: {
    title: "HAPPY 100K!",
    scale: 0.9,
    x: 550,
    y: 100,
    filename: "happy 100k.png",
  },
  // 27: {
  //   title: "WE ALWAYS !CHIMP",
  //   scale: 0.9,
  //   x: 550,
  //   y: 100,
  //   filename: "WE ALWAYS !CHIMP.gif",
  // },
  28: {
    title: "WELCOME!",
    scale: 0.7,
    x: 600,
    y: 100,
    filename: "welcome!.png",
  },
  29: {
    title: "THANKS!",
    scale: 0.7,
    x: 600,
    y: 100,
    filename: "thanks.png",
  },
  30: {
    title: "LFCHIMP!",
    scale: 0.7,
    x: 600,
    y: 100,
    filename: "LFCHIMP.png",
  },
  31: {
    title: "WEN MINT?",
    scale: 0.7,
    x: 600,
    y: 100,
    filename: "wen mint.png",
  },
  32: {
    title: "FEELING !CHIMPISH",
    scale: 0.8,
    x: 650,
    y: 70,
    filename: "feeling chimpish.png",
  },
  33: {
    title: "WE LOVE $PENGU",
    scale: 0.9,
    x: 700,
    y: 80,
    filename: "we love pengu.png",
  },
  34: {
    title: "$PENGU TO THE MOON!",
    scale: 0.9,
    x: 700,
    y: 80,
    filename: "pengu to the moon.png",
  },
  35: {
    title: "HAPPY CHRISTMAS EVE!",
    scale: 0.9,
    x: 550,
    y: 100,
    filename: "Happy Christmas Eve.png",
  },
  36: {
    title: "MERRY CHRISTMAS!",
    scale: 0.8,
    x: 600,
    y: 100,
    filename: "merry christmas.png",
  },
  37: {
    title: "MERRY CHIMPMAS!",
    scale: 0.8,
    x: 400,
    y: 100,
    filename: "Merry Chimpmas.png",
  },
};
